os: linux
dist: bionic
language: ruby

# Travis doesn't build gh-pages by default:
# https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
branches:
  only:
    - gh-pages
    - /.*/

jobs:
  fast_finish: true

  include:
    - stage: Build
      name: Build using Bundler
      install: bundle install --jobs=3 --retry=3
      script: bundle exec jekyll build --config _config.yml,_config_dev.yml --drafts
    - name: Build using latest github-pages
      install:
        # `jekyll build` seems to be using Bundler if Gemfile is present:
        - rm -f -- Gemfile Gemfile.lock
        - gem install github-pages
      script: jekyll build
