baseurl: /sorting_algorithms
gems: [jekyll-paginate]
paginate: 10
include_comments: true
bootstrap_version: 3.3.6
jquery_version: 1.11.3
html5shiv_version: 3.7.2
respond_version: 1.4.2
minified_externals: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - serve.bat
  - README.md
