# Jekyll
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor/

# jekyll-github-metadata
repository: egor-tensin/sorting-algorithms
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@9c44060f0d9dd530a4d90c635da7b83935a1ec19

# egor-tensin/jekyll-theme
bootstrap_version: 3.3.7
jquery_version: 1.12.4
html5shiv_version: 3.7.3
respond_version: 1.4.2

minified_externals: true

project:
  name: Sorting algorithms
  description: Getting the hang out of (sorting) algorithms
baseurl: /sorting-algorithms
personal_info:
  name: Egor Tensin
  email: Egor.Tensin@gmail.com
