# Jekyll
baseurl: /sorting-algorithms

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/sorting-algorithms
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@6bf7c39c874004dd87d4c661018acf2285c8e135

# Theme settings
settings:
  project:
    name: Sorting algorithms
    description: Getting the hang out of (sorting) algorithms
    license: MIT License
    license_file: LICENSE.txt
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
  3rdparty:
    versions:
      bootstrap: 3.4.1
      jquery: 1.12.4
      html5shiv: 3.7.3
      respond: 1.4.2
    minified: true
