# Jekyll
baseurl: /sorting-algorithms

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/sorting-algorithms
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@937c2703df1dde8a7318cfa9b7318a0bf202b4cc

# Theme settings
settings:
  project:
    name: Sorting algorithms
    description: Getting the hang out of (sorting) algorithms
    license: MIT License
    license_file: LICENSE.txt
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
