gems:
  - jekyll-paginate
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - serve.bat
  - README.md

paginate: 10

include_comments: true
minified_externals: true

bootstrap_version: 3.3.6
jquery_version: 1.11.3
html5shiv_version: 3.7.2
respond_version: 1.4.2

project:
  name: Sorting algorithms
  description: Getting the hang out of (sorting) algorithms
baseurl: /sorting-algorithms
repository: egor-tensin/sorting-algorithms
personal_info:
  name: Egor Tensin
  email: Egor.Tensin@gmail.com
