# Jekyll
baseurl: /sorting-algorithms

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/sorting-algorithms
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@f4d1c0b5c2d5ae41faa2c3e7a8f58204a6ea74da

# Theme settings
settings:
  project:
    name: Sorting algorithms
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
  links:
    - {rel: apple-touch-icon, sizes: 180x180, href: /assets/favicon/apple-touch-icon.png}
    - {rel: icon, type: image/png, sizes: 32x32, href: /assets/favicon/favicon-32x32.png}
    - {rel: icon, type: image/png, sizes: 16x16, href: /assets/favicon/favicon-16x16.png}
    - {rel: manifest, href: /assets/favicon/site.webmanifest}
