name: Jekyll

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 4:30 AM on Thursday (somewhat randomly chosen).
    - cron: '30 4 * * 4'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        ruby-version: [2.5, 2.6]
        version: [Gemfile, latest]
        include:
          - {version: Gemfile, gemfile: Gemfile}
          - {version: latest, gemfile: .ci/Gemfile}
    runs-on: ubuntu-18.04
    name: 'Build / ${{ matrix.ruby-version }} / ${{ matrix.version }}'
    env:
      BUNDLE_GEMFILE: '${{ matrix.gemfile }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby-version }}'
          bundler-cache: true
      - name: jekyll build
        run: bundle exec jekyll build --drafts
      - name: Check integrity
        run: |
          nohup bundle exec jekyll serve --drafts --baseurl '' &
          sleep 3 && wget --no-verbose --recursive --convert-links --adjust-extension --directory-prefix=/tmp -- http://localhost:4000/
