name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-18.04
    name: 'Python ${{ matrix.python-version }}'
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: ./.ci/plot.sh
